/**
 * @file rmdev_test_framework.h
 * @author DuYicheng
 * @date 2025-07-19
 * @brief 不带前缀的 rmdev 测试框架头文件
 */

#pragma once
#ifndef RMDEV_TEST_FRAMEWORK_H
#define RMDEV_TEST_FRAMEWORK_H

#include "rmdev_test_framework-with_prefix.h"

#define TEST_SUIT       RMDEV_TEST_TEST_SUIT

#define TEST_CASE_BEGIN RMDEV_TEST_TEST_CASE_BEGIN
#define TEST_CASE_END   RMDEV_TEST_TEST_CASE_END

#define RUN_SUIT        RMDEV_TEST_RUN_SUIT
#define RUN_SUIT_F      RMDEV_TEST_RUN_SUIT_F

#define EXPECT_TRUE     RMDEV_TEST_EXPECT_TRUE
#define EXPECT_FALSE    RMDEV_TEST_EXPECT_FALSE
#define ASSERT_TRUE     RMDEV_TEST_ASSERT_TRUE
#define ASSERT_FALSE    RMDEV_TEST_ASSERT_FALSE

#define INT_EXPECT_EQ   RMDEV_TEST_INT_EXPECT_EQ
#define INT_EXPECT_NE   RMDEV_TEST_INT_EXPECT_NE
#define INT_EXPECT_GT   RMDEV_TEST_INT_EXPECT_GT
#define INT_EXPECT_LT   RMDEV_TEST_INT_EXPECT_LT
#define INT_EXPECT_GE   RMDEV_TEST_INT_EXPECT_GE
#define INT_EXPECT_LE   RMDEV_TEST_INT_EXPECT_LE
#define INT_ASSERT_EQ   RMDEV_TEST_INT_ASSERT_EQ
#define INT_ASSERT_NE   RMDEV_TEST_INT_ASSERT_NE
#define INT_ASSERT_GT   RMDEV_TEST_INT_ASSERT_GT
#define INT_ASSERT_LT   RMDEV_TEST_INT_ASSERT_LT
#define INT_ASSERT_GE   RMDEV_TEST_INT_ASSERT_GE
#define INT_ASSERT_LE   RMDEV_TEST_INT_ASSERT_LE

#define UINT_EXPECT_EQ  RMDEV_TEST_UINT_EXPECT_EQ
#define UINT_EXPECT_NE  RMDEV_TEST_UINT_EXPECT_NE
#define UINT_EXPECT_GT  RMDEV_TEST_UINT_EXPECT_GT
#define UINT_EXPECT_LT  RMDEV_TEST_UINT_EXPECT_LT
#define UINT_EXPECT_GE  RMDEV_TEST_UINT_EXPECT_GE
#define UINT_EXPECT_LE  RMDEV_TEST_UINT_EXPECT_LE
#define UINT_ASSERT_EQ  RMDEV_TEST_UINT_ASSERT_EQ
#define UINT_ASSERT_NE  RMDEV_TEST_UINT_ASSERT_NE
#define UINT_ASSERT_GT  RMDEV_TEST_UINT_ASSERT_GT
#define UINT_ASSERT_LT  RMDEV_TEST_UINT_ASSERT_LT
#define UINT_ASSERT_GE  RMDEV_TEST_UINT_ASSERT_GE
#define UINT_ASSERT_LE  RMDEV_TEST_UINT_ASSERT_LE

#define EXPECT_STREQ    RMDEV_TEST_EXPECT_STREQ
#define ASSERT_STREQ    RMDEV_TEST_ASSERT_STREQ

#define FP_EXPECT_EQ    RMDEV_TEST_FP_EXPECT_EQ
#define FP_EXPECT_NE    RMDEV_TEST_FP_EXPECT_NE
#define FP_EXPECT_GT    RMDEV_TEST_FP_EXPECT_GT
#define FP_EXPECT_LT    RMDEV_TEST_FP_EXPECT_LT
#define FP_EXPECT_GE    RMDEV_TEST_FP_EXPECT_GE
#define FP_EXPECT_LE    RMDEV_TEST_FP_EXPECT_LE
#define FP_ASSERT_EQ    RMDEV_TEST_FP_ASSERT_EQ
#define FP_ASSERT_NE    RMDEV_TEST_FP_ASSERT_NE
#define FP_ASSERT_GT    RMDEV_TEST_FP_ASSERT_GT
#define FP_ASSERT_LT    RMDEV_TEST_FP_ASSERT_LT
#define FP_ASSERT_GE    RMDEV_TEST_FP_ASSERT_GE
#define FP_ASSERT_LE    RMDEV_TEST_FP_ASSERT_LE

#define MESSAGE         RMDEV_TEST_MESSAGE

#endif  // !RMDEV_TEST_FRAMEWORK_H
